// Seed generated from Travell Bee's JustDial catalogue.
// Region-grouped: substantial regions PUBLISHED, thin regions DRAFT.
// Packages carry real price + description; duration/itinerary/images are
// placeholders for the client to complete in admin before publishing.
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const PLACEHOLDER_ITINERARY = [
  { day: 1, title: "Arrival & orientation", description: "Arrive at your destination, complete the hotel check-in, and unwind after your journey. Spend the evening exploring the nearby surroundings or relaxing at your accommodation before the adventure begins." },
];

const DESTINATIONS = [
  {
    slug: "himachal-pradesh",
    name: "Himachal Pradesh",
    code: "HP",
    tagline: "Himalayan valleys & hill towns",
    description: "Mcleodganj, a serene hill station located in Himachal Pradesh, India, is known for its Tibetan culture and stunning natural beauty. As the residence of the Dalai Lama, it offers visitors a glimpse into Tibetan Buddhism with the Namgyal Monastery and the Tsuglagkhang Temple complex. The town is surrounded by lush forests and offers numerous trekking opportunities, including the trek to Triund Hill, which provides breathtaking views of the Dhauladhar Range. Visitors can also explore local markets, enjoy Tibetan cuisine, and experience peaceful walks along the trails.",
    coverImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23",
    published: true,
    packages: [
      {
        slug: "himachal-pradesh-spiti-valley",
        title: "Spiti Valley Package",
        durationDays: 4,
        priceInInr: 18000,
        summary: "Spiti Valley, located in Himachal Pradesh, is known for its rugged landscapes, ancient monasteries, and unique Tibetan culture. Key attractions include the Key Monastery, Chandratal Lake, and the village of Kaza. The valley offers opportunities for trekking, mountaineering, and exploring remote villages. Spiti's high-altitude desert terrain and serene environment provide a stark contrast to…",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-manali",
        title: "Manali Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Experience the Majesty of Manali. Breathtaking Views and Thrilling Adventures. Explore the beauty of Manali, nestled in the Himalayas. Our customizable packages offer a variety of activities, from relaxing in nature to engaging in adventurous pursuits. Perfect for solo travelers, couples, families, and groups.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-kullu-manali",
        title: "Kullu Manali Package",
        durationDays: 4,
        priceInInr: 10800,
        summary: "Explore Kullu Manali's Himalayan Paradise with Our Customizable Packages. Discover the breathtaking landscapes of Kullu Manali, where snow-capped peaks meet lush valleys and charming villages. Whether you're a solo traveler, couple, family, or group, our Kullu Manali Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-himachal-pradesh",
        title: "Himachal Pradesh Package",
        durationDays: 4,
        priceInInr: 10800,
        summary: "Himachal Pradesh is a perfect mix of adventure and serenity. Explore stunning landscapes with snow-covered peaks, pine forests, and sparkling rivers. Visit popular spots like Shimla, Manali, and Dharamshala for trekking, skiing, and more. Whether you're an adventure enthusiast or seeking peace, Himachal offers diverse experiences for everyone.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-mcleodganj",
        title: "Mcleodganj Package",
        durationDays: 4,
        priceInInr: 5400,
        summary: "Mcleodganj, a serene hill station located in Himachal Pradesh, India, is known for its Tibetan culture and stunning natural beauty. As the residence of the Dalai Lama, it offers visitors a glimpse into Tibetan Buddhism with the Namgyal Monastery and the Tsuglagkhang Temple complex. The town is surrounded by lush forests and offers numerous trekking opportunities, including the trek to Triund…",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-banjar",
        title: "Banjar Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Banjar, located in Himachal Pradesh, India, is known for its scenic beauty and tranquil environment. Key attractions include the Great Himalayan National Park, a UNESCO World Heritage Site offering trekking and wildlife viewing opportunities. Visitors can also explore the picturesque villages and enjoy the serene landscapes of the Tirthan Valley.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-shimla",
        title: "Shimla Package",
        durationDays: 4,
        priceInInr: 5400,
        summary: "Explore the Charm of Shimla. A Hill Station Paradise. Discover the colonial charm and stunning landscapes of Shimla. Our customizable packages ensure you experience the best of Shimla, catering to various travel styles and group sizes.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-tabo",
        title: "Tabo Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Tabo, located in the Indian state of Himachal Pradesh, is known for its ancient Buddhist monasteries. The Tabo Monastery, often referred to as the \"Ajanta of the Himalayas,\" is a prominent attraction featuring ancient murals, thangkas, and statues. The monastery complex includes the Temple of the Dakinis and the Monastic Enclave, offering insights into Tibetan Buddhism. Tabo serene environment…",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-chamba",
        title: "Chamba Package",
        durationDays: 4,
        priceInInr: 8550,
        summary: "Chamba, situated in Himachal Pradesh, India, is known for its historical and cultural attractions. Major sites include the Chamba Palace, a historic royal residence with stunning architecture, and the Lakshmi Narayan Temple, a prominent religious site. Visitors can explore local markets for traditional crafts, enjoy scenic views, and experience the cultural heritage of the region through its…",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-charang",
        title: "Charang Package",
        durationDays: 4,
        priceInInr: 31500,
        summary: "Charang, located in Himachal Pradesh, India, is a serene village known for its picturesque landscapes and cultural experiences. Key attractions include the Charang Temple, a historic site with intricate carvings, and the Charang Valley, offering stunning views and opportunities for trekking. Visitors can explore the local culture, enjoy traditional cuisine, and experience the natural beauty of…",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-chintpurni",
        title: "Chintpurni Package",
        durationDays: 4,
        priceInInr: 3600,
        summary: "Chintpurni, located in Himachal Pradesh, India, is known for its religious significance and scenic surroundings. The primary attraction is the Chintpurni Temple, dedicated to the Goddess Chintpurni and a major pilgrimage site. Visitors can explore the local markets for spiritual souvenirs, enjoy the serene environment, and experience the religious and cultural heritage of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-chitkul",
        title: "Chitkul Package",
        durationDays: 4,
        priceInInr: 10800,
        summary: "Chitkul, located in Himachal Pradesh, India, is the last inhabited village on the Indo-Tibetan border and known for its stunning natural beauty. Major attractions include the Chitkul Village itself, offering picturesque views of the Himalayas, and the Baspa River, ideal for nature walks and photography. Visitors can explore the local culture, enjoy traditional cuisine, and experience the…",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-jispa",
        title: "Jispa Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Jispa, situated in Himachal Pradesh, India, is a scenic destination in the Lahaul Valley. Key attractions include the Bharatpur Wildlife Sanctuary, known for its diverse flora and fauna, and the Jispa Village, offering stunning Himalayan views. Visitors can enjoy nature walks, explore local markets, and experience the serene environment of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-manikaran",
        title: "Manikaran Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Manikaran, located in Himachal Pradesh, India, is known for its hot springs and religious sites. Major attractions include the Manikaran Sahib Gurudwara, a significant Sikh temple, and the Hot Springs, offering natural thermal baths. Visitors can explore the gurudwara, enjoy the hot springs, and experience the natural and spiritual beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-mashobra",
        title: "Mashobra Package",
        durationDays: 4,
        priceInInr: 7650,
        summary: "Mashobra, located in Himachal Pradesh, India, offers a serene environment and natural beauty. Major attractions include the Mashobra Ridge, providing panoramic views, and the Sipur Waterfall, a scenic spot for relaxation. Visitors can enjoy nature walks, explore local markets, and experience the tranquility of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-nalagarh",
        title: "Nalagarh Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Nalagarh, situated in Himachal Pradesh, India, is known for its historical fort and natural beauty. Key attractions include the Nalagarh Fort, offering panoramic views and historical insights, and the Barog, a picturesque hill station. Visitors can explore the fort, enjoy the scenic beauty of Barog, and experience local culture.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-pragpur",
        title: "Pragpur Package",
        durationDays: 4,
        priceInInr: 4500,
        summary: "Pragpur, located in Himachal Pradesh, India, is known for its historical and cultural heritage. Major attractions include the Pragpur Village, known for its traditional architecture and heritage, and the Tashi Jong Monastery, a peaceful place for spiritual retreats. Visitors can explore the village, visit the monastery, and experience local culture.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-rohru",
        title: "Rohru Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Rohru, located in Himachal Pradesh, India, offers natural beauty and outdoor activities. Key attractions include the Sutlej River, ideal for river rafting, and the Hatu Peak, offering scenic views and trekking opportunities. Visitors can enjoy river rafting, explore the peak, and experience the local environment.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-bharmour",
        title: "Bharmour Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Bharmour, located in Himachal Pradesh, India, is known for its natural beauty and spiritual significance. Major attractions include the Chaurasi Temple Complex, a significant pilgrimage site with ancient temples, and the Bharmour Wildlife Sanctuary, offering opportunities for nature walks and wildlife viewing. Visitors can enjoy the serene environment and explore local markets for traditional…",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-fagu",
        title: "Fagu Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Fagu, located in Himachal Pradesh, India, is known for its natural beauty and tranquil environment. Major attractions include the Fagu Village, offering scenic views of the Himalayas, and the Apple Orchards, where visitors can enjoy fresh produce and nature walks. Visitors can explore the serene surroundings, enjoy local markets, and experience the natural beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-kangra",
        title: "Kangra Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Kangra, situated in Himachal Pradesh, India, offers a range of historical and natural attractions. Key sites include the Kangra Fort, a historic structure with architectural significance, and the Masroor Rock Cut Temples, ancient temples with historical carvings. Visitors can explore local markets, enjoy traditional Himachali cuisine, and experience the historical and natural beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-kaza",
        title: "Kaza Package",
        durationDays: 4,
        priceInInr: 25200,
        summary: "Kaza, situated in Himachal Pradesh, India, is a high-altitude town in the Spiti Valley. Key attractions include the Key Monastery, an important Buddhist monastery, and the Hikkim Village, known for being one of the highest inhabited villages in the world. Visitors can enjoy trekking, explore the local culture, and experience the stunning landscapes of the Spiti Valley.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-naggar",
        title: "Naggar Package",
        durationDays: 4,
        priceInInr: 8100,
        summary: "Naggar, located in Himachal Pradesh, India, is known for its scenic beauty and historical sites. Major attractions include the Naggar Castle, offering panoramic views and historical insights, and the Roerich Art Gallery, showcasing the works of artist Nicholas Roerich. Visitors can explore the castle, visit the gallery, and enjoy the natural beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-sirmaur",
        title: "Sirmaur Package",
        durationDays: 4,
        priceInInr: 7650,
        summary: "Sirmaur, located in Himachal Pradesh, India, offers natural beauty and cultural experiences. Major attractions include the Nahan Fort, known for its historical significance, and the Local Temples and Lakes for spiritual and relaxation experiences. Visitors can explore the fort, visit the temples, and enjoy the lakes.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-tosh",
        title: "Tosh Package",
        durationDays: 4,
        priceInInr: 13500,
        summary: "Tosh, a village in Himachal Pradesh, India, is known for its breathtaking natural beauty and tranquil environment. Nestled in the Parvati Valley, Tosh offers stunning views of the surrounding mountains, lush green landscapes, and opportunities for trekking and nature walks. Visitors can enjoy the serene atmosphere, explore local cafes, and experience the charm of this picturesque Himalayan…",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-una",
        title: "Una Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Una, a city in Himachal Pradesh, India, is known for its natural beauty and cultural significance. Visitors can explore attractions such as the historic Jwalamukhi Temple, the picturesque Una Lake, and enjoy the scenic beauty of the surrounding hills and countryside. The city offers opportunities for outdoor activities, cultural exploration, and local cuisine experiences.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-khajjiar",
        title: "Khajjiar Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Khajjiar, situated in Himachal Pradesh, India, is often referred to as the ini Switzerland of Indiadue to its picturesque landscapes. Major attractions include the Khajjiar Lake, surrounded by lush green meadows, and the Khajji Nag Temple, dedicated to the local deity. Visitors can enjoy nature walks, paragliding, and explore the scenic beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-shimla-kullu-manali",
        title: "Shimla Kullu Manali Package",
        durationDays: 4,
        priceInInr: 16200,
        summary: "Explore the Majesty of Himachal Pradesh with Our Shimla Kullu Manali Tour Packages. Experience the breathtaking beauty of the Himalayas with our customizable tours to Shimla, Kullu, and Manali. From snow-capped peaks to lush valleys, our packages offer a perfect blend of adventure, nature, and cultural experiences.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-parwanoo",
        title: "Parwanoo Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Parwanoo, located in Himachal Pradesh, India, is known for its scenic beauty and outdoor activities. Key attractions include the Timber Trail, offering cable car rides with panoramic views, and the Shivalik Hills, ideal for nature walks and picnics. Visitors can enjoy the cable car ride, explore the hills, and relax in the serene environment.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-darcha",
        title: "Darcha Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Darcha is a remote village in Himachal Pradesh, India, serving as a starting point for treks into the Zanskar Valley. Known for its rugged terrain and breathtaking landscapes, visitors can embark on trekking adventures, explore the local monasteries, and experience the tranquil environment of the Indian Himalayas.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-kinnaur",
        title: "Kinnaur Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Kinnaur, situated in Himachal Pradesh, India, is known for its stunning landscapes and cultural heritage. Key attractions include the Sangla Valley, offering breathtaking views and trekking opportunities, and the Kinnaur Kailash, a sacred mountain with religious significance. Visitors can enjoy nature walks, explore local villages, and experience the natural beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-mandi",
        title: "Mandi Package",
        durationDays: 4,
        priceInInr: 8550,
        summary: "Mandi, situated in Himachal Pradesh, India, offers a range of natural and historical attractions. Key sites include the Prashar Lake, known for its scenic beauty and trekking opportunities, and the Mandi Temple, a significant religious site. Visitors can explore local markets, enjoy traditional Himachali cuisine, and experience the natural and cultural beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-palampur",
        title: "Palampur Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Palampur, located in Himachal Pradesh, India, offers a range of natural and cultural attractions. Key sites include the Palampur Tea Gardens, known for their scenic beauty, and the Baijnath Temple, a historic religious site. Visitors can enjoy the tea gardens, explore the temple, and experience the natural beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
      {
        slug: "himachal-pradesh-hamirpur",
        title: "Hamirpur Package",
        durationDays: 4,
        priceInInr: 0,
        summary: "Hamirpur, situated in Himachal Pradesh, India, offers a range of natural and cultural experiences. Key attractions include the Nadaun Fort, a historic structure with architectural interest, and the Baba Balak Nath Temple, a significant religious site. Visitors can explore local markets, enjoy traditional Himachali cuisine, and experience the natural beauty of the region.",
        themes: ["Hill stations", "Adventure"],
        published: true,
      },
    ],
  },
  {
    slug: "goa",
    name: "Goa",
    code: "GOA",
    tagline: "Beaches, forts & Portuguese charm",
    description: "Calangute, a town in North Goa, is known for its beautiful beach, vibrant nightlife, and water sports. Key attractions include the Calangute Beach, St. Alex Church, and the bustling markets. The town offers a blend of natural beauty, recreational activities, and cultural experiences. Calangute's diverse cuisine, lively beach shacks, and vibrant festivals provide a rich and immersive experience. The town's dynamic atmosphere, coupled with its stunning landscapes and recreational opportunities, makes it a popular destination for both domestic and international tourists seeking a tropic",
    coverImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2",
    published: true,
    packages: [
      {
        slug: "goa-anjuna",
        title: "Anjuna Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Anjuna, a village in North Goa, is known for its beautiful beach, vibrant flea market, and bohemian vibe. Key attractions include the Anjuna Beach, Anjuna Flea Market, and the Chapora Fort. The village offers a blend of natural beauty, cultural experiences, and modern amenities. Anjuna's diverse cuisine, lively nightlife, and vibrant festivals provide a rich and immersive experience. The…",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-calangute",
        title: "Calangute Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Calangute, a town in North Goa, is known for its beautiful beach, vibrant nightlife, and water sports. Key attractions include the Calangute Beach, St. Alex Church, and the bustling markets. The town offers a blend of natural beauty, recreational activities, and cultural experiences. Calangute's diverse cuisine, lively beach shacks, and vibrant festivals provide a rich and immersive…",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-candolim",
        title: "Candolim Package",
        durationDays: 4,
        priceInInr: 7650,
        summary: "Relax on the peaceful beaches of Candolim in North Goa, where sun, sand, and serenity meet. Enjoy water sports, beachside cafes, and historic landmarks like Fort Aguada. The vibe is laid-back yet close to the action of bustling Baga and Calangute. This package suits travelers seeking a balanced beach holidayideal for couples, families, and groups looking to unwind and explore Goa's charm.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-north-goa",
        title: "North Goa Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "North Goa is the heart of excitement, offering golden beaches, vibrant flea markets, and buzzing nightlife. Visit popular spots like Baga, Anjuna, and Vagator, enjoy adventure water sports, or relax in beach shacks with music and seafood. From forts to full moon parties, North Goa has it all. This package is ideal for young travelers, groups, and those looking for a fun, energetic beach holiday.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-old-goa",
        title: "Old Goa Package",
        durationDays: 4,
        priceInInr: 4500,
        summary: "Step into Goa's colonial past with a tour of Old Goa, known for its magnificent churches and UNESCO-listed sites. Marvel at Basilica of Bom Jesus, Se Cathedral, and ornate baroque architecture. Surrounded by history and spirituality, this serene destination is perfect for heritage lovers, pilgrims, and anyone wanting to experience the soul of Goa beyond beaches and nightlife.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-panaji",
        title: "Panaji Package",
        durationDays: 4,
        priceInInr: 13500,
        summary: "Panaji, the capital of Goa, is known for its Portuguese architecture, vibrant markets, and scenic waterfronts. Key attractions include the Our Lady of the Immaculate Conception Church, Miramar Beach, and the Latin Quarter of Fontainhas. The city offers a blend of historical landmarks, cultural experiences, and modern amenities. Panaji's diverse cuisine, bustling markets, and vibrant festivals…",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-goa",
        title: "Goa Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Goa is an enchanting destination, offering beautiful beaches, vibrant nightlife, and rich colonial history. Whether you're seeking adventure through water sports, relaxation on sandy shores, or exploring forts and churches, Goa has something for every type of traveler. Our Goa packages are designed to give you the best of this coastal paradise.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-arpora",
        title: "Arpora Package",
        durationDays: 4,
        priceInInr: 10800,
        summary: "Arpora, located in Goa, India, is a charming village known for its vibrant markets and nightlife. Key attractions include the Arpora Saturday Night Market, a bustling bazaar offering local crafts, food, and entertainment. The nearby Baga Beach and Anjuna Beach are popular for their scenic beauty and water sports. Arpora is a great destination for those seeking a mix of relaxation and lively…",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-bardez",
        title: "Bardez Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Bardez, situated in Goa, India, is known for its beautiful beaches and vibrant culture. Major attractions include Calangute Beach and Anjuna Beach, popular for their scenic beauty and water sports. Visitors can explore the Chapora Fort for panoramic views and enjoy the lively atmosphere of the local markets and beachside restaurants.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-bicholim",
        title: "Bicholim Package",
        durationDays: 4,
        priceInInr: 8100,
        summary: "Bicholim, located in Goa, India, offers a blend of natural beauty and cultural experiences. Major attractions include the Mayem Lake, a serene spot for relaxation and boating, and the Saptakoteshwar Temple, an important religious site. Visitors can explore local markets for Goan handicrafts, enjoy the nearby Baga Beach, and experience the vibrant Goan culture through its festivals and cuisine.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-colva",
        title: "Colva Package",
        durationDays: 4,
        priceInInr: 8100,
        summary: "Colva, situated in Goa, India, is famous for its beautiful beaches and vibrant atmosphere. Major attractions include the Colva Beach, known for its white sand and water sports, and the Our Lady of Mercy Church, a historical religious site. Visitors can relax on the beach, explore local markets for souvenirs, and enjoy Goan cuisine at beachside shacks and restaurants.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-dona-paula",
        title: "Dona Paula Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Dona Paula, located in Goa, India, is famous for its beautiful beaches and scenic views. Major attractions include the Dona Paula Beach, known for its golden sands and water sports, and the Dona Paula Viewpoint, offering panoramic views of the Arabian Sea. Visitors can relax on the beach, explore local markets, and enjoy Goan cuisine at beachfront restaurants.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-miramar",
        title: "Miramar Package",
        durationDays: 4,
        priceInInr: 8100,
        summary: "Miramar, situated in Goa, India, is famous for its beautiful beach and vibrant atmosphere. Key attractions include the Miramar Beach, known for its scenic beauty, and the Goa Science Centre, offering interactive exhibits. Visitors can relax on the beach, enjoy water sports, and explore local markets.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-morjim",
        title: "Morjim Package",
        durationDays: 4,
        priceInInr: 8550,
        summary: "Morjim, located in Goa, India, is known for its beautiful beach and tranquil environment. Major attractions include the Morjim Beach, known for its serene atmosphere, and the Morjim-Ashwem Beach Stretch, offering opportunities for relaxation and beach activities. Visitors can enjoy beach activities, explore local markets, and experience the coastal charm of the region.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-paroda",
        title: "Paroda Package",
        durationDays: 4,
        priceInInr: 13500,
        summary: "Paroda, located in Goa, India, is known for its peaceful environment and local attractions. Major sites include the Shree Shantadurga Temple, a significant religious site, and the local Goan villages offering a glimpse into traditional life. Visitors can explore the temple, enjoy village walks, and experience Goan culture.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-salcete",
        title: "Salcete Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Salcete, a district in Goa, India, is known for its beautiful beaches, historic sites, and vibrant local culture. Visitors can explore popular beaches such as Colva and Benaulim, visit the historic churches and temples, and enjoy the lively local markets and festivals. The district also offers opportunities for water sports, relaxation, and experiencing Goan cuisine.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-vasco-da-gama",
        title: "Vasco Da Gama Package",
        durationDays: 4,
        priceInInr: 7650,
        summary: "Vasco Da Gama, a city in Goa, India, is known for its historical significance and scenic beauty. Attractions include the scenic Vasco Beach, the historic St. Andrew's Church, and the vibrant local markets. Visitors can explore the beach, enjoy local seafood, and experience the historical and cultural heritage of this charming Goan city.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-benaulim",
        title: "Benaulim Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Benaulim, situated in Goa, India, is known for its beautiful beaches and relaxed atmosphere. Benaulim Beach is a popular destination for sunbathing and swimming, while the nearby Majorda Beach offers similar relaxation opportunities. Visitors can explore local markets for souvenirs, enjoy beachside dining, and experience the vibrant Goan culture.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-kolva",
        title: "Kolva Package",
        durationDays: 4,
        priceInInr: 5400,
        summary: "Kolva, situated in Goa, India, is known for its beautiful beaches and relaxation opportunities. Major attractions include the Kolva Beach, offering white sands and water activities, and the Salcete Market, known for shopping and local cuisine. Visitors can enjoy beach activities, explore local markets, and experience the relaxed beach lifestyle of Goa.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-mapusa",
        title: "Mapusa Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Mapusa, situated in Goa, India, is known for its vibrant markets and local attractions. Key sites include the Mapusa Market, offering a range of goods and local products, and the St. Cajetan Church, a historic church with architectural interest. Visitors can explore the market, enjoy local cuisine, and experience the vibrant atmosphere of the region.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-pernem",
        title: "Pernem Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Pernem, located in Goa, India, is known for its serene beaches and local attractions. Key sites include the Pernem Beach, offering relaxation and water activities, and the Shri Mahalaxmi Temple, a significant religious site. Visitors can enjoy the beach, explore the temple, and experience local Goan culture.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-ponda",
        title: "Ponda Package",
        durationDays: 4,
        priceInInr: 5400,
        summary: "Ponda, located in Goa, India, offers a range of cultural and historical attractions. Major sites include the Shri Manguesh Temple, a significant religious site, and the Goa Chitra Museum, showcasing local history and culture. Visitors can explore the temple, visit the museum, and enjoy traditional Goan cuisine.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-vaddem",
        title: "Vaddem Package",
        durationDays: 4,
        priceInInr: 12600,
        summary: "Vaddem, a small town in Goa, India, is a peaceful retreat known for its natural beauty and relaxed atmosphere. Visitors can explore the local beaches, enjoy the serene environment, and experience the laid-back lifestyle of this charming Goan town. Nearby attractions include the bustling markets of Vasco Da Gama and the scenic beaches of South Goa.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-porvorim",
        title: "Porvorim Package",
        durationDays: 4,
        priceInInr: 6750,
        summary: "Porvorim, a town in Goa, India, offers a blend of natural beauty and modern amenities. Located close to the state capital, Panaji, Porvorim provides access to the beautiful beaches of Goa, such as Calangute and Baga. Visitors can explore local attractions including the historic St. Augustine Tower, enjoy vibrant nightlife, and experience Goan cuisine at various restaurants and beach shacks.…",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-assagaon",
        title: "Assagaon Package",
        durationDays: 4,
        priceInInr: 18000,
        summary: "Assagaon, located in Goa, India, is a quaint village known for its laid-back atmosphere and traditional Goan charm. Attractions include the Assagao Church, an example of colonial architecture, and local Goan Cuisine served in traditional eateries. The village offers a peaceful retreat from the more touristy areas of Goa and is close to popular beaches like Vagator Beach and Anjuna Beach.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-verem",
        title: "Verem Package",
        durationDays: 4,
        priceInInr: 8100,
        summary: "Verem, a small village in Goa, India, is known for its peaceful environment and natural beauty. Visitors can explore the local Verem Beach, enjoy the serene surroundings, and experience the laid-back lifestyle of this quaint Goan village. The area offers opportunities for relaxation, beach activities, and exploring nearby natural sites.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
      {
        slug: "goa-south-goa",
        title: "South Goa Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "South Goa, a popular tourist destination in Goa, India, is known for its beautiful beaches and relaxed atmosphere. Visitors can enjoy the serene beaches of Palolem, Agonda, and Colva, explore historic sites like the Cabo de Rama Fort, and indulge in Goan cuisine and local markets. The region offers a tranquil escape from the bustling North Goa.",
        themes: ["Beaches", "Heritage"],
        published: true,
      },
    ],
  },
  {
    slug: "lakshadweep",
    name: "Lakshadweep",
    code: "LAK",
    tagline: "Coral islands & lagoons",
    description: "Minicoy Island, part of Lakshadweep, is known for its unique culture, pristine beaches, and vibrant marine life. The island has a distinct Maldivian influence, evident in its language, customs, and architecture. Key attractions include the historic Minicoy Lighthouse, offering panoramic views, and the beautiful beaches ideal for water sports and relaxation. Minicoy's coral reefs are perfect for snorkeling and diving, while its traditional dance forms and cultural festivals provide a glimpse into the island's rich heritage.",
    coverImage: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7",
    published: true,
    packages: [
      {
        slug: "lakshadweep-minicoy",
        title: "Minicoy Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Minicoy Island, part of Lakshadweep, is known for its unique culture, pristine beaches, and vibrant marine life. The island has a distinct Maldivian influence, evident in its language, customs, and architecture. Key attractions include the historic Minicoy Lighthouse, offering panoramic views, and the beautiful beaches ideal for water sports and relaxation. Minicoy's coral reefs are perfect…",
        themes: ["Beaches", "Adventure"],
        published: true,
      },
      {
        slug: "lakshadweep-kalpeni",
        title: "Kalpeni Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Kalpeni, located in the Lakshadweep Islands, India, is known for its pristine beaches and water activities. Major attractions include the Kalpeni Beach, known for its white sands and clear waters, and the Lakshadweep Marine Museum, showcasing local marine life. Visitors can enjoy snorkeling, explore local markets, and experience the natural beauty of the islands.",
        themes: ["Beaches", "Adventure"],
        published: true,
      },
      {
        slug: "lakshadweep-kadmat",
        title: "Kadmat Package",
        durationDays: 4,
        priceInInr: 27000,
        summary: "Kadmat is an island in the Lakshadweep Archipelago of India, renowned for its pristine beaches and crystal-clear waters. It is a perfect destination for scuba diving and snorkeling enthusiasts due to its vibrant coral reefs and abundant marine life. The island offers tranquil beach resorts and opportunities for water sports, including kayaking and windsurfing. Visitors can also explore the…",
        themes: ["Beaches", "Adventure"],
        published: true,
      },
      {
        slug: "lakshadweep-amini",
        title: "Amini Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Amini, located in the Lakshadweep Islands, India, is known for its pristine beaches and vibrant marine life. The Amini Beach offers a tranquil environment for relaxation and water activities. Visitors can explore the local Marine Life and enjoy the stunning coral reefs and clear blue waters. Amini is a perfect destination for those seeking a peaceful beach getaway and marine adventures.",
        themes: ["Beaches", "Adventure"],
        published: true,
      },
    ],
  },
  {
    slug: "kerala",
    name: "Kerala",
    code: "KER",
    tagline: "Backwaters, hills & Ayurveda",
    description: "Neeleshwar is a serene coastal village located in Kerala, India. It is known for its tranquil beaches, traditional Kerala architecture, and cultural heritage. Visitors can relax on the pristine Neeleshwar Beach, enjoy peaceful walks along the shoreline, and explore local seafood delicacies. The Neeleshwar Hermitage offers a peaceful retreat with yoga and meditation sessions. The village also features beautiful backwaters and lush green surroundings that reflect the serene and unspoiled charm of Kerala. It an ideal destination for those seeking a peaceful escape and a chance to experi",
    coverImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944",
    published: true,
    packages: [
      {
        slug: "kerala-kerala",
        title: "Kerala Package",
        durationDays: 4,
        priceInInr: 14400,
        summary: "Kerala, renowned for its tranquil backwaters, lush hill stations, and golden beaches, offers an ideal vacation experience. Our Kerala packages provide an opportunity to explore the unique blend of natural beauty, Ayurvedic treatments, and rich cultural heritage. Whether it's a houseboat cruise or visiting tea gardens, Kerala promises a memorable escape.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-munnar",
        title: "Munnar Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Experience Munnar's Tea Country Charm with Our Customizable Packages. Immerse yourself in the breathtaking beauty of Munnar, where lush green tea plantations meet majestic hills and cascading waterfalls. Whether you're a solo traveler, couple, family, or group, our Munnar Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-aluva",
        title: "Aluva Package",
        durationDays: 4,
        priceInInr: 4500,
        summary: "Aluva, situated in Kerala, India, is known for its scenic beauty and religious significance. The Aluva Manappuram, a sacred sandbank along the Periyar River, is a popular spot for religious ceremonies and spiritual reflection. Visitors can also explore the St. Antony's Church and enjoy the lush greenery and tranquil environment of the region. Aluva is a peaceful destination with opportunities…",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-cochin",
        title: "Cochin Package",
        durationDays: 4,
        priceInInr: 5850,
        summary: "Explore Cochin with Our Customizable Sightseeing Packages. Experience the vibrant culture and history of Cochin, a port city on the Malabar Coast. Whether you're a solo traveler, couple, family, or group, our Cochin Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-bekal",
        title: "Bekal Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Bekal, located in Kerala, India, is famous for its historic fort and scenic beaches. The Bekal Fort, a well-preserved 17th-century fort, offers stunning views of the Arabian Sea and the surrounding landscape. Visitors can relax on Bekal Beach, explore the nearby Kappil Beach, and enjoy the natural beauty of the region.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-kasaragod",
        title: "Kasaragod Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Kasaragod, situated in Kerala, India, is known for its natural beauty and historical sites. Key attractions include the Bekal Fort, a historic fort with scenic views, and the Kasaragod Beach, offering relaxation and coastal activities. Visitors can explore local markets, enjoy traditional Kerala cuisine, and experience the natural and historical richness of the region.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-maradu",
        title: "Maradu Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Maradu, located in Kerala, India, offers a mix of natural beauty and local experiences. Major attractions include the Maradu Beach, offering relaxation and scenic views, and the Maradu Church, a historic site with cultural significance. Visitors can enjoy beach activities, explore local markets, and experience the coastal charm of the region.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-mulanthuruthy",
        title: "Mulanthuruthy Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Mulanthuruthy, located in Kerala, India, is known for its historical and cultural sites. Major attractions include the Mulanthuruthy Temple, a significant religious site, and the Mulanthuruthy Palace, offering insights into local history. Visitors can explore the temple, visit the palace, and enjoy traditional Kerala cuisine.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-neeleshwar",
        title: "Neeleshwar Package",
        durationDays: 4,
        priceInInr: 29700,
        summary: "Neeleshwar is a serene coastal village located in Kerala, India. It is known for its tranquil beaches, traditional Kerala architecture, and cultural heritage. Visitors can relax on the pristine Neeleshwar Beach, enjoy peaceful walks along the shoreline, and explore local seafood delicacies. The Neeleshwar Hermitage offers a peaceful retreat with yoga and meditation sessions. The village also…",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-kappad",
        title: "Kappad Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Kappad, a beach town in Kerala, India, is famous for its historic significance and scenic coastline. The Kappad Beach is a major attraction, known for its serene environment and historical landmarks. It was here that Vasco da Gama first landed in India in 1498, marking the beginning of the sea route from Europe to India. Kappad offers a tranquil beach experience combined with historical…",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-vythiri-taluk",
        title: "Vythiri Taluk Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Vythiri Taluk, located in the Wayanad district of Kerala, India, is renowned for its lush green landscapes, serene forests, and natural attractions. Visitors can explore Pookode Lake, trek to the Edakkal Caves, and enjoy the scenic beauty of Wayanad hills and waterfalls. The area offers a peaceful retreat with opportunities for outdoor activities and nature walks.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-pathanamthitta",
        title: "Pathanamthitta Package",
        durationDays: 4,
        priceInInr: 12600,
        summary: "Pathanamthitta, located in Kerala, India, is known for its natural beauty and religious sites. Key attractions include the Sabarimala Temple, a major pilgrimage destination, and the Perunthenaruvi Waterfalls, offering a refreshing natural experience. Visitors can explore the temple, enjoy the waterfalls, and experience the local culture.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-thiruvalla",
        title: "Thiruvalla Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Thiruvalla, located in Kerala, India, is known for its cultural heritage and serene environment. The town is famous for the Parumala Church, a significant pilgrimage site for Christians, and the beautiful Punnamada Lake. Visitors can explore traditional Kerala architecture, enjoy the local cuisine, and experience the tranquil surroundings of this historic town.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-changanacherry",
        title: "Changanacherry Package",
        durationDays: 4,
        priceInInr: 0,
        summary: "Changanacherry, located in Kerala, India, is known for its historical and cultural significance. Major attractions include the St. Thomas Church, a historic church with beautiful architecture, and the Changanacherry Palace, showcasing the region royal heritage. Visitors can explore local markets, enjoy traditional Keralite cuisine, and visit the Punnamada Lake for boat rides and relaxation.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
      {
        slug: "kerala-kodungallur",
        title: "Kodungallur Package",
        durationDays: 4,
        priceInInr: 0,
        summary: "Kodungallur, situated in Kerala, India, is known for its historical and religious sites. Key attractions include the Kodungallur Bhagavathy Temple, a significant Hindu pilgrimage site, and the Cheraman Juma Masjid, one of the oldest mosques in India. Visitors can explore local markets, enjoy traditional Kerala cuisine, and experience the cultural and historical richness of the region.",
        themes: ["Hill stations", "Family"],
        published: true,
      },
    ],
  },
  {
    slug: "sikkim-darjeeling",
    name: "Sikkim & Darjeeling",
    code: "SIK",
    tagline: "Tea gardens & the Eastern Himalayas",
    description: "Explore Darjeeling's Majestic Hills with Our Customizable Packages. Discover the allure of Darjeeling, where snow-capped mountains meet rolling tea gardens and vibrant monasteries. Whether you're a solo traveler, couple, family, or group, our Darjeeling Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
    coverImage: "https://images.unsplash.com/photo-1544634076-a90160ddf22e",
    published: false,
    packages: [
      {
        slug: "sikkim-darjeeling-darjeeling",
        title: "Darjeeling Package",
        durationDays: 4,
        priceInInr: 8100,
        summary: "Explore Darjeeling's Majestic Hills with Our Customizable Packages. Discover the allure of Darjeeling, where snow-capped mountains meet rolling tea gardens and vibrant monasteries. Whether you're a solo traveler, couple, family, or group, our Darjeeling Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Hill stations"],
        published: false,
      },
    ],
  },
  {
    slug: "ladakh",
    name: "Ladakh",
    code: "LEH",
    tagline: "High-altitude desert & monasteries",
    description: "Hemis is a village in the Ladakh region of northern India, known for the Hemis Monastery, one of the largest and wealthiest monasteries in Ladakh. The monastery, established in the 11th century, is famous for its annual Hemis Festival, which features traditional dances, music, and religious ceremonies. The village also serves as a base for trekking and exploring the stunning landscapes of the Ladakh region, including the Zanskar Valley and Markha Valley.",
    coverImage: "https://images.unsplash.com/photo-1601821765780-754fa98637c1",
    published: true,
    packages: [
      {
        slug: "ladakh-ladakh",
        title: "Ladakh Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Ladakh, known for its breathtaking landscapes, tranquil monasteries, and rugged terrains, offers a unique adventure for those seeking peace and adventure alike. From exploring Leh to trekking around Pangong Lake, and biking along the highest motorable passes, our Ladakh packages cater to those seeking a surreal escape in the Himalayas.",
        themes: ["Adventure"],
        published: true,
      },
      {
        slug: "ladakh-alchi",
        title: "Alchi Package",
        durationDays: 4,
        priceInInr: 10800,
        summary: "Alchi, located in Ladakh, India, is known for its ancient Buddhist monasteries and serene landscapes. The Alchi Monastery, one of the oldest Buddhist monasteries in Ladakh, is famous for its well-preserved murals, statues, and unique architecture. Visitors can explore the Alchi Choskor Monastic Complex and enjoy the peaceful surroundings of the Indus River valley. Alchi offers a tranquil…",
        themes: ["Adventure"],
        published: true,
      },
      {
        slug: "ladakh-stok-kangri",
        title: "Stok Kangri Package",
        durationDays: 4,
        priceInInr: 45000,
        summary: "Stok Kangri, located in Ladakh, India, is a popular destination for trekkers and adventure enthusiasts. The mountain offers a challenging trek with stunning views of the Himalayan range. Visitors can experience high-altitude trekking, explore the rugged terrain, and enjoy breathtaking vistas of snow-capped peaks and valleys. The trek is ideal for those seeking a challenging adventure and a…",
        themes: ["Adventure"],
        published: true,
      },
      {
        slug: "ladakh-shey",
        title: "Shey Package",
        durationDays: 4,
        priceInInr: 27000,
        summary: "Shey, situated in Ladakh, India, offers stunning natural landscapes and cultural experiences. Major attractions include the Shey Palace, known for its architectural beauty, and the Shey Monastery for spiritual insights. Visitors can explore the palace, visit the monastery, and enjoy the serene environment.",
        themes: ["Adventure"],
        published: true,
      },
      {
        slug: "ladakh-zanskar",
        title: "Zanskar Package",
        durationDays: 4,
        priceInInr: 31500,
        summary: "Zanskar, a remote region in Ladakh, India, is renowned for its rugged landscapes and unique cultural experiences. Visitors can explore attractions like the ancient Buddhist monasteries, the scenic Zanskar River, and partake in adventurous activities such as trekking, river rafting, and exploring the stunning landscapes of the Zanskar Valley.",
        themes: ["Adventure"],
        published: true,
      },
      {
        slug: "ladakh-hemis",
        title: "Hemis Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Hemis is a village in the Ladakh region of northern India, known for the Hemis Monastery, one of the largest and wealthiest monasteries in Ladakh. The monastery, established in the 11th century, is famous for its annual Hemis Festival, which features traditional dances, music, and religious ceremonies. The village also serves as a base for trekking and exploring the stunning landscapes of the…",
        themes: ["Adventure"],
        published: true,
      },
      {
        slug: "ladakh-padum",
        title: "Padum Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Padum, situated in Ladakh, India, is known for its natural beauty and cultural sites. Major attractions include the Zanskar Valley, offering trekking and scenic views, and the Stongdey Monastery, a significant Buddhist site. Visitors can enjoy trekking, explore the monastery, and experience the serene environment.",
        themes: ["Adventure"],
        published: true,
      },
      {
        slug: "ladakh-tingmosgang",
        title: "Tingmosgang Package",
        durationDays: 4,
        priceInInr: 13500,
        summary: "Tingmosgang, situated in Ladakh, India, offers stunning landscapes and cultural experiences. Key attractions include the Tingmosgang Monastery, a significant Buddhist site, and Local Trekking Trails for adventure seekers. Visitors can explore the monastery, enjoy treks, and experience Ladakhi culture.",
        themes: ["Adventure"],
        published: true,
      },
    ],
  },
  {
    slug: "uttarakhand",
    name: "Uttarakhand",
    code: "UK",
    tagline: "Char Dham & Himalayan retreats",
    description: "Embark on a Sacred Pilgrimage to the Chardham with Our Customizable Packages. Experience the divine blessings of the four sacred shrines. Yamunotri, Gangotri, Kedarnath, and Badrinath. Whether you're a solo traveler, couple, family, or group, our Chardham Yatra Packages with Customizable Facilities ensure a comfortable and memorable spiritual journey.",
    coverImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23",
    published: true,
    packages: [
      {
        slug: "uttarakhand-uttarakhand",
        title: "Uttarakhand Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Uttarakhand is a land of majestic mountains, lush forests, and tranquil lakes. Whether it's a pilgrimage to Haridwar and Rishikesh, a serene retreat in Nainital, or trekking through the Garhwal Himalayas, Uttarakhand offers a peaceful escape amidst nature. With adventure and spirituality in equal measure, Uttarakhand is perfect for every traveler.",
        themes: ["Hill stations", "Heritage"],
        published: true,
      },
      {
        slug: "uttarakhand-kedarnath",
        title: "Kedarnath Package",
        durationDays: 4,
        priceInInr: 13500,
        summary: "Explore Kedarnath with Our Customizable Pilgrimage Packages. Embark on a spiritual journey to Kedarnath, one of the holiest sites in Hinduism. Whether you're a solo traveler or part of a group, our Kedarnath Yatra Packages provide a seamless and memorable experience, focusing on your spiritual needs.",
        themes: ["Hill stations", "Heritage"],
        published: true,
      },
      {
        slug: "uttarakhand-chardham",
        title: "Chardham Package",
        durationDays: 4,
        priceInInr: 27000,
        summary: "Embark on a Sacred Pilgrimage to the Chardham with Our Customizable Packages. Experience the divine blessings of the four sacred shrines. Yamunotri, Gangotri, Kedarnath, and Badrinath. Whether you're a solo traveler, couple, family, or group, our Chardham Yatra Packages with Customizable Facilities ensure a comfortable and memorable spiritual journey.",
        themes: ["Hill stations", "Heritage"],
        published: true,
      },
      {
        slug: "uttarakhand-badrinath",
        title: "Badrinath Package",
        durationDays: 4,
        priceInInr: 6750,
        summary: "Explore Badrinath with Our Customizable Pilgrimage Packages. Embark on a spiritual journey to Badrinath, one of the holiest sites in Hinduism. Whether you're a solo traveler or part of a group, our Badrinath Yatra Packages provide a seamless and memorable experience, focusing on your spiritual needs.",
        themes: ["Hill stations", "Heritage"],
        published: true,
      },
      {
        slug: "uttarakhand-kund",
        title: "Kund Package",
        durationDays: 4,
        priceInInr: 0,
        summary: "Kund, located in Uttarakhand, India, is known for its serene environment and natural beauty. Major attractions include the Kund Waterfall, a picturesque spot for relaxation, and the Sutol Village, offering a glimpse into local village life. Visitors can enjoy nature walks, explore local markets, and experience the tranquility of the region.",
        themes: ["Hill stations", "Heritage"],
        published: true,
      },
    ],
  },
  {
    slug: "rajasthan",
    name: "Rajasthan",
    code: "RAJ",
    tagline: "Forts, palaces & desert cities",
    description: "Explore the breathtaking beauty and rich cultural heritage of North India with our exclusive tour packages. Experience the majestic landscapes of the Himalayas, the historical marvels of Delhi, and the enchanting palaces of Rajasthan. Our curated itineraries offer a blend of adventure, spirituality, and leisure, ensuring every traveler finds something to cherish. Enjoy guided tours, comfortable accommodations, and authentic local cuisine, all tailored to provide an unforgettable journey through one of India's most diverse and vibrant regions.",
    coverImage: "https://images.unsplash.com/photo-1477587458883-47145ed94245",
    published: true,
    packages: [
      {
        slug: "rajasthan-jaipur",
        title: "Jaipur Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Explore Jaipur with Our Customizable Sightseeing Packages. Experience the majestic forts, vibrant bazaars, and rich culture of Jaipur, the Pink City. Whether you're a solo traveler, couple, family, or group, our Jaipur Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Heritage", "Family"],
        published: true,
      },
      {
        slug: "rajasthan-udaipur",
        title: "Udaipur Package",
        durationDays: 4,
        priceInInr: 7200,
        summary: "Explore Udaipur with Our Customizable Sightseeing Packages. Experience the romance of Udaipur, the \"City of Lakes\", with its majestic palaces and stunning lakes. Whether you're a solo traveler, couple, family, or group, our Udaipur Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Heritage", "Family"],
        published: true,
      },
      {
        slug: "rajasthan-jaisalmer",
        title: "Jaisalmer Package",
        durationDays: 4,
        priceInInr: 5400,
        summary: "Experience the Golden Desert Magic with Our Jaisalmer Tour Packages. Embark on an unforgettable journey to Jaisalmer, the Golden City. Our customizable packages offer a unique opportunity to explore the majestic forts, sand dunes, and experience the vibrant Rajasthani culture.",
        themes: ["Heritage", "Family"],
        published: true,
      },
      {
        slug: "rajasthan-rajasthan",
        title: "Rajasthan Package",
        durationDays: 4,
        priceInInr: 16200,
        summary: "Embark on a Royal Rajasthan Adventure with Our Customizable Packages. Journey through the majestic land of Rajasthan, where forts and palaces whisper tales of bygone eras and vibrant culture thrives. Whether you're a solo traveler, couple, family, or group, our Rajasthan Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Heritage", "Family"],
        published: true,
      },
      {
        slug: "rajasthan-north-india",
        title: "North India Package",
        durationDays: 4,
        priceInInr: 13500,
        summary: "Explore the breathtaking beauty and rich cultural heritage of North India with our exclusive tour packages. Experience the majestic landscapes of the Himalayas, the historical marvels of Delhi, and the enchanting palaces of Rajasthan. Our curated itineraries offer a blend of adventure, spirituality, and leisure, ensuring every traveler finds something to cherish. Enjoy guided tours,…",
        themes: ["Heritage", "Family"],
        published: true,
      },
    ],
  },
  {
    slug: "tamil-nadu",
    name: "Tamil Nadu",
    code: "TN",
    tagline: "Temples & hill stations",
    description: "Explore Rameswaram with Our Customizable Sightseeing Packages. Embark on a pilgrimage to Rameswaram, a sacred island with ancient temples and stunning beaches. Whether you're a solo traveler, couple, family, or group, our Rameswaram Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
    coverImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220",
    published: false,
    packages: [
      {
        slug: "tamil-nadu-ooty",
        title: "Ooty Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Discover the Queen of Hills. Ooty's Natural Beauty and Serene Charm. Experience the beauty of Ooty, a hill station known for its tea gardens, stunning views, and pleasant climate. Our customizable packages cater to all types of travelers, allowing you to explore Ooty at your own pace.",
        themes: ["Heritage", "Hill stations"],
        published: false,
      },
      {
        slug: "tamil-nadu-rameswaram",
        title: "Rameswaram Package",
        durationDays: 4,
        priceInInr: 4500,
        summary: "Explore Rameswaram with Our Customizable Sightseeing Packages. Embark on a pilgrimage to Rameswaram, a sacred island with ancient temples and stunning beaches. Whether you're a solo traveler, couple, family, or group, our Rameswaram Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Heritage", "Hill stations"],
        published: false,
      },
    ],
  },
  {
    slug: "kashmir",
    name: "Kashmir",
    code: "KAS",
    tagline: "Valleys, lakes & Mughal gardens",
    description: "Explore Srinagar with Our Customizable Sightseeing Packages. Experience the breathtaking beauty of Srinagar, the \"City of Lakes\", nestled amidst the majestic Himalayas. Whether you're a solo traveler, couple, family, or group, our Srinagar Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
    coverImage: "https://images.unsplash.com/photo-1566837945700-30057527ade0",
    published: true,
    packages: [
      {
        slug: "kashmir-srinagar",
        title: "Srinagar Package",
        durationDays: 4,
        priceInInr: 9000,
        summary: "Explore Srinagar with Our Customizable Sightseeing Packages. Experience the breathtaking beauty of Srinagar, the \"City of Lakes\", nestled amidst the majestic Himalayas. Whether you're a solo traveler, couple, family, or group, our Srinagar Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Hill stations", "Honeymoon"],
        published: true,
      },
      {
        slug: "kashmir-kashmir",
        title: "Kashmir Package",
        durationDays: 4,
        priceInInr: 13500,
        summary: "Experience the Paradise on Earth. Kashmir's Majestic Beauty and Serenity. Discover the breathtaking beauty of Kashmir, known for its stunning landscapes, serene lakes, and snow-capped mountains. Our customizable packages offer various options for exploring this enchanting destination.",
        themes: ["Hill stations", "Honeymoon"],
        published: true,
      },
      {
        slug: "kashmir-amarnath",
        title: "Amarnath Package",
        durationDays: 4,
        priceInInr: 13500,
        summary: "Embark on a Spiritual Journey to Amarnath with Our Customizable Packages. Experience the divine blessings of Amarnath Ji. Whether you're a solo traveler, couple, family, or group, our Amarnath Yatra Packages with Customizable Facilities ensure a comfortable and safe pilgrimage.",
        themes: ["Hill stations", "Honeymoon"],
        published: true,
      },
    ],
  },
  {
    slug: "karnataka",
    name: "Karnataka",
    code: "KAR",
    tagline: "Coffee country & heritage",
    description: "Explore Coorg with Our Customizable Sightseeing Packages. Experience the breathtaking beauty of Coorg, the 'Scotland of India'. Whether you're a solo traveler, couple, family, or group, our Coorg Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
    coverImage: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99",
    published: false,
    packages: [
      {
        slug: "karnataka-coorg",
        title: "Coorg Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Explore Coorg with Our Customizable Sightseeing Packages. Experience the breathtaking beauty of Coorg, the 'Scotland of India'. Whether you're a solo traveler, couple, family, or group, our Coorg Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
        themes: ["Hill stations"],
        published: false,
      },
    ],
  },
  {
    slug: "andaman",
    name: "Andaman",
    code: "AND",
    tagline: "Islands, reefs & white sand",
    description: "Explore the Andaman & Nicobar Islands. Pristine Beaches and Underwater Wonders. Discover the stunning beauty of the Andaman & Nicobar Islands, known for their pristine beaches, vibrant coral reefs, and diverse marine life. Our customizable packages offer a variety of island-hopping and adventure activities.",
    coverImage: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7",
    published: false,
    packages: [
      {
        slug: "andaman-andaman",
        title: "Andaman Package",
        durationDays: 4,
        priceInInr: 22500,
        summary: "Explore the Andaman & Nicobar Islands. Pristine Beaches and Underwater Wonders. Discover the stunning beauty of the Andaman & Nicobar Islands, known for their pristine beaches, vibrant coral reefs, and diverse marine life. Our customizable packages offer a variety of island-hopping and adventure activities.",
        themes: ["Beaches", "Adventure"],
        published: false,
      },
    ],
  },
  {
    slug: "andhra-pradesh",
    name: "Andhra Pradesh",
    code: "AP",
    tagline: "Temples & the Eastern Ghats",
    description: "Explore Araku with Our Customizable Sightseeing Packages. Experience the beauty of Araku Valley, nestled in the Eastern Ghats. Known for its lush green hills, coffee plantations, and tribal culture, Araku offers a refreshing escape. Whether you're a solo traveler, couple, family, or group, our Araku Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
    coverImage: "https://images.unsplash.com/photo-1600100397608-f010cff4a8a5",
    published: false,
    packages: [
      {
        slug: "andhra-pradesh-tirupati",
        title: "Tirupati Package",
        durationDays: 4,
        priceInInr: 5400,
        summary: "Plan Your Spiritual Journey to Tirupati. A Sacred Destination. Embark on a spiritual journey to Tirupati, home to the sacred Venkateswara Temple. Our packages cater to pilgrims seeking a meaningful and comfortable experience.",
        themes: ["Heritage"],
        published: false,
      },
      {
        slug: "andhra-pradesh-araku",
        title: "Araku Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Explore Araku with Our Customizable Sightseeing Packages. Experience the beauty of Araku Valley, nestled in the Eastern Ghats. Known for its lush green hills, coffee plantations, and tribal culture, Araku offers a refreshing escape. Whether you're a solo traveler, couple, family, or group, our Araku Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your…",
        themes: ["Heritage"],
        published: false,
      },
    ],
  },
  {
    slug: "uttar-pradesh",
    name: "Uttar Pradesh",
    code: "UP",
    tagline: "Temple towns & the Ganga",
    description: "Explore Vrindavan with Our Customizable Spiritual Packages. Discover the spiritual heart of Vrindavan, a sacred town associated with Lord Krishna. Experience the divine atmosphere, visit ancient temples, and participate in spiritual activities. Our customizable packages cater to spiritual seekers.",
    coverImage: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc",
    published: false,
    packages: [
      {
        slug: "uttar-pradesh-vrindavan",
        title: "Vrindavan Package",
        durationDays: 4,
        priceInInr: 1800,
        summary: "Explore Vrindavan with Our Customizable Spiritual Packages. Discover the spiritual heart of Vrindavan, a sacred town associated with Lord Krishna. Experience the divine atmosphere, visit ancient temples, and participate in spiritual activities. Our customizable packages cater to spiritual seekers.",
        themes: ["Heritage"],
        published: false,
      },
    ],
  },
  {
    slug: "madhya-pradesh",
    name: "Madhya Pradesh",
    code: "MP",
    tagline: "Temples & the Narmada",
    description: "Explore Omkareshwar with Our Customizable Pilgrimage & Nature Packages. Discover the spiritual and scenic wonders of Omkareshwar, nestled on the banks of the Narmada River. Whether you're a pilgrim seeking blessings or a nature enthusiast, our Omkareshwar Tours with Customizable Package Facilities offer a unique experience tailored to your preferences.",
    coverImage: "https://images.unsplash.com/photo-1600100397608-f010cff4a8a5",
    published: false,
    packages: [
      {
        slug: "madhya-pradesh-ujjain",
        title: "Ujjain Package",
        durationDays: 4,
        priceInInr: 3600,
        summary: "Ujjain. A Spiritual Journey to the Kumbh Mela City. Experience the sacred city of Ujjain, a significant Hindu pilgrimage site and host to the Kumbh Mela. Our customizable packages cater to spiritual seekers and travelers.",
        themes: ["Heritage"],
        published: false,
      },
      {
        slug: "madhya-pradesh-omkareshwar",
        title: "Omkareshwar Package",
        durationDays: 4,
        priceInInr: 4500,
        summary: "Explore Omkareshwar with Our Customizable Pilgrimage & Nature Packages. Discover the spiritual and scenic wonders of Omkareshwar, nestled on the banks of the Narmada River. Whether you're a pilgrim seeking blessings or a nature enthusiast, our Omkareshwar Tours with Customizable Package Facilities offer a unique experience tailored to your preferences.",
        themes: ["Heritage"],
        published: false,
      },
    ],
  },
  {
    slug: "maharashtra",
    name: "Maharashtra",
    code: "MH",
    tagline: "Hill retreats & pilgrim towns",
    description: "Explore Mahabaleshwar with Our Customizable Sightseeing Packages. Experience the magic of Mahabaleshwar, a hill station in the Western Ghats known for its stunning views, waterfalls, and strawberry farms. Whether you're a solo traveler, couple, family, or group, our Mahabaleshwar Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your preferences.",
    coverImage: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f",
    published: false,
    packages: [
      {
        slug: "maharashtra-mahabaleshwar",
        title: "Mahabaleshwar Package",
        durationDays: 4,
        priceInInr: 6300,
        summary: "Explore Mahabaleshwar with Our Customizable Sightseeing Packages. Experience the magic of Mahabaleshwar, a hill station in the Western Ghats known for its stunning views, waterfalls, and strawberry farms. Whether you're a solo traveler, couple, family, or group, our Mahabaleshwar Sightseeing Tours with Customizable Package Facilities ensure you get the most out of your trip, tailored to your…",
        themes: ["Heritage", "Hill stations"],
        published: false,
      },
      {
        slug: "maharashtra-shirdi",
        title: "Shirdi Package",
        durationDays: 4,
        priceInInr: 2250,
        summary: "Discover Inner Peace. Spiritual Tour Packages to Shirdi. Visit Shirdi, the abode of Sai Baba, and experience the spiritual serenity of this sacred place. Our customizable packages offer a peaceful and enriching journey.",
        themes: ["Heritage", "Hill stations"],
        published: false,
      },
    ],
  },
]

async function main() {
  for (const d of DESTINATIONS) {
    const dest = await prisma.destination.upsert({
      where: { slug: d.slug },
      update: {},
      create: {
        slug: d.slug, name: d.name, code: d.code, tagline: d.tagline,
        description: d.description, coverImage: d.coverImage,
      },
    });

    for (const p of d.packages) {
      await prisma.package.upsert({
        where: { slug: p.slug },
        update: {},
        create: {
          slug: p.slug,
          title: p.title,
          destinationId: dest.id,
          durationDays: p.durationDays,
          priceInInr: p.priceInInr,
          coverImage: d.coverImage,        // reuse destination cover until real photos added
          summary: p.summary,
          inclusions: ["Hotel stay", "Daily breakfast", "Transfers"],
          exclusions: ["Flights", "Personal expenses"],
          itinerary: PLACEHOLDER_ITINERARY,
          themes: p.themes,
          status: p.published ? "PUBLISHED" : "DRAFT",
          featured: false,
        },
      });
    }
    console.log(`${d.published ? "PUBLISHED" : "DRAFT    "}  ${d.name}  (${d.packages.length} packages)`);
  }
  console.log("\nSeed complete.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });